#!/usr/bin/env node --harmony

var program = require('commander');

program
    .version('0.0.1')
    .command('start <path>')
    .action(function(path){
        console.log(this);
        var DaemonRunner = require('../lib/daemon/daemon_runner.js');
        var daemonPath = require('path').resolve(process.cwd(), path);

        var Daemon = require(daemonPath);
        var options = {};
        var runner = new DaemonRunner(Daemon, options);
        runner.start();
    })

program
    .version('0.0.1')
    .command('daemonize <job>')
    .action(function(path){
        console.log(this);
        var DaemonRunner = require('../lib/daemon/daemon_runner.js');
        var jobPath = require('path').resolve(process.cwd(), path);
        var GeneralDaemon = require('../lib/daemons/GeneralJobDaemon.js')
        var Job = require(jobPath);
        var options = {jobClass: Job};
        var runner = new DaemonRunner(GeneralDaemon, options);
        runner.start();
    })

program.parse(process.argv);
