#!/usr/bin/env node --harmony

var program = require('commander'),
    inquirer = require('inquirer'),
    readYaml = require('read-yaml');
var env = (process.env.NODE_ENV || "development").toLowerCase();
var config = readYaml.sync(require('path').resolve('./config/wechat.yml'))[env];
var wechatAPI = require('co-wechat-api');
if ( !config ) { throw `./config/wechat.yml#[${env}] is required`}
program
    .version('0.0.1')
    .command('menu')
    .action(function(){
        require('inquirer').prompt([
            {name: 'baseurl', message: 'baseurl', required: true},
            {name: 'withLogout', message: 'with logout'}
        ], function(answers) {
            api = new wechatAPI(config.appId, config.appSecret);
            var baseurl = answers.baseurl;
            var menu = JSON.parse(`{
                "button": [
                    {
                        "type": "view",
                        "name": "付停车费",
                        // "url": "${baseurl}/static/html/paychoice.html"
                        "url": "${baseurl}/wechat/action?toUrl=/wechat-view/paychoice.html"
                    },
                    {
                        "name": "个人中心",
                        "sub_button": [
                            {
                                "type": "view",
                                "name": "我的优惠券",
                                "url": "${baseurl}/static/html/coupon.html"
                            },
                            {
                                "type": "view",
                                "name": "我的车辆",
                                "url": "${baseurl}/static/html/car.html"
                            },
                            {
                                "type": "view",
                                "name": "车牌认证",
                                "url": "${baseurl}/static/html/carAuth.html"
                            },
                            {
                                "type": "view",
                                "name": "停车记录",
                                "url": "${baseurl}/static/html/parkingRecord.html"
                            }
                        ]
                    },
                    {
                        "type": "view",
                        "name": "使用帮助",
                        "url": "${baseurl}/static/html/help.html"
                    }
                ]
            }`);
            if ( answers.withLogout ) {
                menu.button[2].sub_button.push(
                            {
                                "type":"view",
                                "name": "登出",
                                "url": `${baseurl}/session/logout`
                            }
                            );
            }

            console.log("creating menu: ", menu);
            // console.log("creating menu: ", menu.button[1].sub_button);
            //console.log("creating menu: ", menu.button[2].sub_button);
            api.createMenu(menu)(function(err, result, response){
                console.log(result)
                if ( result ) {
                    console.log(result);
                    console.log(result.errmsg);
                    return process.exit(result.errcode);
                }
                process.exit(0);
            })
        });
    })

program.parse(process.argv);
